title = "PowerHorseEngine"  # From Git
gitRepoUrl = "https://github.com/lanzoinc/PowerHorseEngine" # From Git

gitSourceBranch = "main"
changelog = false

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

# From git:
organizationName = "Lanzo"
projectName = "PowerHorseEngine"
url = "https://LanzoInc.github.io"
tagline = "Your project's tagline"

[footer]
style = "dark"

copyright = "Copyright © 2023 Olanzo James"

[[footer.links]]
title = "Socials"

[[footer.links.items]]
label = "Twitter"
href = "https://twitter.com/lanzoinc"
[[footer.links.items]]
label = "Instagram"
href = "https://instagram.com/lanzo.exe"
[[footer.links.items]]
label = "ROBLOX"
href = "https://twitter.com/lanzoinc"

[[footer.links]]
title = "Other Projects"
[[footer.links.items]]
label = "View Projects"
href = "https://lanzo.vercel.app/Projects"

[[classOrder]]
section = "Classes"
classes = [
"Accordion","AccordionGroup","ActiveTrade","AICharacterRig","AIHuman","ActionMenu","ActionMenuAction","AppBar","AudioChannel",
"Badge","BaseCharacterRig","BaseGui","BaseText",
"Button","Checkbox","CustomClass","ClientBackpackProxy","CloseButton",
"CharacterRig","Cutscene","CurrencyIndicator","CurrencyDropIndicator","DamageIndicator","DataStore",
"DatePicker","DirectionalArrowClass","DropdownButton","GridPlacement","HitMarker","ListItem","LocationIndicator",
"MenuItem","FadeTransition","Frame","GUI","Image",
"Modal","Navigator","NotificationResponse","PHePluginAppHandler","PHePluginLibraryObject","PHePluginStudioTool","PHeSignal","Promise","PromptResponse",
"Pseudo","PromptSheet","ProximityPrompt","RInstance","Servant","State","SpatialAreaClass","StateManagerClass","ToolTip",
"Waypoint","Widget","PingReader","Transition","Tween","TabGroup","TextComponent","Toast",
"Toggle","TextInput","TextSlider","ProgressBar","StackProvider","Portal","NotificationGroup"
]

[[classOrder]]
section = "Services"
classes = [
"AudioService","CoreGuiService","CustomClassService","CoordinateService","ChatTagService","CommandService","CodeService",
"CoreProviderService","ClientBackpackService","ClientService","DataStoreService","ErrorService","EncryptionService","FormatService","GridPlacementService",
"KEYSERVICE","InGamePurchaseService","ModalService","NotificationService","PingService",
"PromptService","PluginService","PseudoService","ReplicationService","SerializationService","SmartTextService","TweenService",
"TextService","TradeService","UserIdService","WaypointService","VoteKickService",
]

[[classOrder]]
section = "Providers"
classes = [
"ContentProvider","LibraryProvider","ModuleFetcher","ModuleFetcherProvider","PropProvider","ServiceProvider","SignalProvider","SpatialArea","ServerBee","ServerBeeClient",
"UtilProvider","ImageProvider","LanzoCoreUtil"
]

[[classOrder]]
section = "Globals"
classes = [
"CutsceneConstructor","Engine","Enumeration","Format","Flags","Theme"
]

[[classOrder]]
section = "Built In Libraries"
classes = [
"Contextor","Collector","DirectionalArrow3D","Sillito","SillitoBranch","StateLibrary","Whiplash","Array","Math","ReClasser"
]

[[classOrder]]
section = "Hooks"
classes = [
"useEffect","useMapping","useComponents","useRender","useRawset"
]

[[classOrder]]
section = "PHe Panel"
classes = [
    "PHePanel"
]

apiCategories = ["Event"]
