title = "PowerHorseEngine"  # From Git
gitRepoUrl = "https://github.com/lanzoinc/PowerHorseEngine" # From Git

gitSourceBranch = "main"
changelog = false

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

# From git:
organizationName = "Lanzo"
projectName = "PowerHorseEngine"
url = "https://LanzoInc.github.io"
# baseUrl = "/PowerHorseEngine"
tagline = "Your project's tagline"

[footer]
style = "dark"
copyright = "Copyright © 2022 Lanzo"

[[footer.links]]
title = "Socials"

[[footer.links.items]]
label = "Twitter"
href = "https://twitter.com/lanzoinc"


[[classOrder]]
section = "Classes"
classes = [
"Accordion","ActionMenu","ActionMenuAction","AppBar","AudioService","BaseGui","BaseText",
"Button","ChannelMethods","Checkbox","CoreGuiService","CustomClass","CustomClassService",
"Cutscene","ErrorService","FadeTransition","FormatService","Frame","GUI","Image","InGamePurchaseService",
"Modal","Navigator","NotificationResponse","PHeSignal","PingService","Promise","PromptResponse","PromptService",
"Pseudo","PseudoService","RInstance","Servant","State","TextService","ToolTip","TradeService","UserIdService",
"Waypoint","WaypointService","Widget",
"NotificationService","PingReader","Transition","Tween","TweenService","TabGroup","CoordinateService","TextComponent","Toast",
"Toggle","TextInput","CommandService"
]

[[classOrder]]
section = "Providers"
classes = [
"LibraryProvider","ModuleFetcher","ServiceProvider","SignalProvider","UtilProvider",
]

[[classOrder]]
section = "Globals"
classes = [
"CutsceneConstructor","Engine","Enumeration","Format","Theme"
]

[[classOrder]]
section = "Built In Libraries"
classes = [
"Collector","Framework","FrameworkClient","FrameworkServer","StateLibrary","Whiplash",
]