title = "PowerHorseEngine"  # From Git
gitRepoUrl = "https://github.com/lanzoinc/PowerHorseEngine" # From Git

gitSourceBranch = "main"
changelog = false

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

# From git:
organizationName = "Lanzo"
projectName = "PowerHorseEngine"
url = "https://LanzoInc.github.io"
# baseUrl = "/PowerHorseEngine"
tagline = "Your project's tagline"

[footer]
style = "dark"

copyright = "Copyright © 2022 Lanzo"

[[footer.links]]
title = "Socials"

[[footer.links.items]]
label = "Twitter"
href = "https://twitter.com/lanzoinc"


[[classOrder]]
section = "Classes"
classes = [
"Accordion","ActionMenu","ActionMenuAction","AppBar","AudioChannel","BaseGui","BaseText",
"Button","Checkbox","CustomClass",
"Cutscene","FadeTransition","Frame","GUI","Image",
"Modal","Navigator","NotificationResponse","PHeSignal","Promise","PromptResponse",
"Pseudo","RInstance","Servant","State","ToolTip",
"Waypoint","Widget","PingReader","Transition","Tween","TabGroup","TextComponent","Toast",
"Toggle","TextInput","TextSlider","ProgressBar","StackProvider","Portal","NotificationGroup"
]

[[classOrder]]
section = "Services"
classes = [
"AudioService","CoreGuiService","CustomClassService","ErrorService","FormatService","InGamePurchaseService","PingService",
"PromptService","PseudoService","TextService","TradeService","UserIdService","WaypointService","NotificationService","TweenService",
"CoordinateService","CommandService","ClientBackpackService","ClientService",
]

[[classOrder]]
section = "Providers"
classes = [
"LibraryProvider","ModuleFetcher","ServiceProvider","SignalProvider","UtilProvider","ImageProvider","LanzoCoreUtil"
]

[[classOrder]]
section = "Globals"
classes = [
"CutsceneConstructor","Engine","Enumeration","Format","Theme"
]

[[classOrder]]
section = "Built In Libraries"
classes = [
"Collector","Framework","FrameworkClient","FrameworkServer","StateLibrary","Whiplash","Array","Math","ReClasser"
]

[[classOrder]]
section = "Hooks"
classes = [
"useEffect","useMapping","useComponents","useRender",
]

[[classOrder]]
section = "PHe Panel"
classes = [
    "PHePanel"
]

apiCategories = ["Event"]
