name: Publish CI

on:
  push:
    branches: [ main, dev ]

jobs:

  development:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/dev' }}

    steps:
    - uses: actions/checkout@v3

<<<<<<< HEAD
    - name: Echo
=======
    - name: Echo Aftman
>>>>>>> main
      run: echo Development pushed

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
<<<<<<< HEAD

=======
    # needs: [build] 
>>>>>>> main
    steps:
    - uses: actions/checkout@v3

    - name: Setup Aftman
      uses: ok-nick/setup-aftman@v0.1.0
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
        trust-check: false

    - name: Install Aftman Toolchains
      run: aftman install

    - name: Rojo output file
      run: rojo build -o PowerHorseEngine.rbxm default.project.json
  
    - name: Publish to Wally
      env: 
        WALLY_TOKEN: ${{ secrets.WALLY_AUTH_TOKEN }}
      run: |
        mkdir =p ~/.wally
        printf "[tokens]\n\"https://api.wally.run/\" = \"%s\"" "$WALLY_TOKEN" >> ~/.wally/auth.toml
        wally publish

    - uses: actions/setup-node@v3
      with:
        cache: npm
        node-version: 16 
    - run: npm ci
    - run: npx semantic-release
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
