name: Publish CI

on:
  push:
    branches: [ main ]

jobs:

  # setup-node:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       node-version: [15.x]
  #       os: [ubuntu-latest, windows-latest]

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js ${{ matrix.os }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - run: npm ci

  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        run: "echo building project"

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.ref == 'refs/heads/main' }}
    # needs: [setup-node]
    steps:
    - uses: actions/checkout@v3

    # - name: Use Node.js ${{ matrix.os }}
    - uses: actions/setup-node@v3
      with:
        cache: npm
        node-version: 16
        # node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npx semantic-release
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
