name: Publish CI

on:
  push:
    branches: [ main ]

jobs:

  # build: 
  #   runs-on: ubuntu-latest
  #   if: ${{ github.ref == 'refs/heads/main' }}
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Setup Aftman
  #       uses: ok-nick/setup-aftman@v0.1.0
  #       with: 
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         trust-check: false

  #     - name: Install Aftman Toolchains
  #       run: aftman install

  #     - name: Install Dependencies
  #       run: wally install

  #     - name: Create Packages Directory
  #       run: mkdir -p Packages

  #     - name: Rojo output file
  #       run: rojo build -o PowerHorseEngine.rbxm default.project.json

  #     - name: Get Release from wally.toml 
  #       uses: SebRollen/toml-action@v1.0.0 
  #       id: read_toml
  #       with: 
  #         file: 'wally.toml'
  #         field: 'package.version'

  #     - name: Publish to Wally
  #       env: 
  #         WALLY_TOKEN: ${{ secrets.WALLY_AUTH_TOKEN }}
  #       run: |
  #         mkdir =p ~/.wally
  #         printf "[tokens]\n\"https://api.wally.run/\" = \"%s\"" "$WALLY_TOKEN" >> ~/.wally/auth.toml
  #         wally publish
  development:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/dev' }}

    steps:
    - uses: actions/checkout@v3

    - name: Log info
      run: echo hello,world 

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    # needs: [build] 
    steps:
    - uses: actions/checkout@v3

    - name: Setup Aftman
      uses: ok-nick/setup-aftman@v0.1.0
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
        trust-check: false

    - name: Install Aftman Toolchains
      run: aftman install

    - name: Rojo output file
      run: rojo build -o PowerHorseEngine.rbxm default.project.json

    - uses: actions/setup-node@v3
      with:
        cache: npm
        node-version: 16
    - run: npm ci
    - run: npx semantic-release
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
