name: Publish CI

on:
  push:
    branches: [ main ]


jobs:

  setup-node:
    runs-on: ${{ matrix.os }}
    stratergy:
      node-version: [15.x]
      os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
        run: npm ci
        run: npm test

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [setup-node]
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.os }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
        - run: npm ci
        - run: npm run semantic-release
